on: [push]

name: Build Docker images

env:
  REGISTRY_USERNAME: ${{ github.actor }}
  REGISTRY_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  REGISTRY_URL: ghcr.io/k8s-devops-tools
  GITHUB_ORGANIZATION: k8s-devops-tools
  KEYLESS: true

jobs:
  images:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        job:
          - base
          - test
      fail-fast: false
    name: images/${{ matrix.job}}
    steps:
      - name: Cancel previous runs
        if: github.event_name == 'pull_request'
        uses: styfle/cancel-workflow-action@0.11.0

      - name: Checkout
        uses: actions/checkout@v3

      # - name: Build ${{ matrix.job }} images
      #   run: |
      #     ${{ github.workspace }}/scripts/build_images.sh \
      #       --tag=${{ matrix.job }}

      - name: SplitTag
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          refIN=${GITHUB_REF##*/}
          arrIN=(${refIN//./ })
          echo "major=${arrIN[0]}" >> $GITHUB_ENV
          echo "minor=${arrIN[0]}.${arrIN[1]}" >> $GITHUB_ENV
          echo "patch=${arrIN[0]}.${arrIN[1]}.${arrIN[2]}" >> $GITHUB_ENV

      - name: Set no tag
        if: startsWith(github.ref, 'refs/tags/v') == false
        run: |
          echo "major=" >> $GITHUB_ENV
          echo "minor=" >> $GITHUB_ENV
          echo "patch=" >> $GITHUB_ENV
        
      - name: Build ${{ matrix.job }} image
        uses: philips-software/docker-ci-scripts@v4.5.0
        with:
          dockerfile: .
          image-name: ${{ matrix.job }}
          tags: "latest ${{ env.major }} ${{ env.minor }} ${{ env.patch }}"
          push-on-git-tag: "true"
          push-branches: main develop
