on: [push]

name: Build Docker images

env:
  REGISTRY_USERNAME: ${{ github.actor }}
  REGISTRY_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  REGISTRY_URL: ghcr.io/organization-here
  GITHUB_ORGANIZATION: organization-here
  KEYLESS: true

jobs:
  test_latest_image:
    name: Test latest image
    runs-on: ubuntu-latest
    container: philipssoftware/node:latest
    steps:
    - name: Build Docker Images
      id: docker
      uses: philips-software/docker-ci-scripts@v4.5.0
      with:
        dockerfile: .
        image-name: image-name-here
        tags: latest 0.1
        push-branches: main develop
